version: '3'
services:
  api-service:
    container_name: api-service
    build:
      context: .
      dockerfile: Dockerfile
    command: 'npm run start:debug'
    restart: always
    env_file:
      - .env
    ports:
      - '3002:3002'
      - '9229:9229'
    volumes:
      - ./:/app
      - '/app/node_modules'
    links:
      - api-service-mongo
      - api-service-postgres
    depends_on:
      - api-service-mongo
      - api-service-postgres

  api-service-mongo:
    image: 'mongo:4.0'
    container_name: api-service-mongo
    ports:
      - '5333:27017'
    volumes:
      - './.data/mongo:/data/db'
      - './.data/mongoconfigdb:/data/configdb'

  api-service-postgres:
    platform: linux/amd64
    image: 'postgres:15'
    container_name: api-service-postgres
    volumes:
      - './.data/postgres:/var/lib/postgresql/data'
    ports:
      - '5434:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
