export enum ERROR_TITLES {
  NON_FOUND_ERROR = 'NOT FOUND ERROR',
  VALIDATION_ERROR = 'VALIDATION ERROR',
  UNAUTHORIZED_ERROR = 'UNAUTHORIZED ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR',
}

export enum ENV {
  DEVELOP = 'DEVELOP',
  TEST = 'TEST',
  PRE_PROD = 'PRE_PROD',
  PROD = 'PROD',
}
