export const PATIENT_DOCS_CATEGORY = [
  'DIAGNOSIS',
  'LAB_RESULTS',
  'OTHERS',
  'PRESCRIPTIONS',
  'X_RAY',
  'ULTRASOUND',
  'CT_SCAN',
  'MRI',
  'BLOOD_TESTS',
  'ECG',
  'ENDOSCOPY',
  'BIOPSY',
];

export const PATIENT_GENDER = ['MALE', 'FEMALE'];
